[build]
  command = "hugo -s exampleSite --themesDir .. -t . --gc --minify --baseURL $DEPLOY_PRIME_URL"
  publish = "exampleSite/public"

[build.environment]
HUGO_VERSION = "0.159.0"
HUGO_ENABLEGITINFO = "true"
